version: "3"
services:
  ipower-db:
    image: mysql:latest
    container_name: ipower-db
    volumes:
      - ./mysql:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_DATABASE: ipowerwww
    command: '--default_authentication_plugin=mysql_native_password'

  ipower-php:
    build:
      context: ./php
    container_name: ipower-php
    depends_on:
      - ipower-db
    volumes:
      - ./wordpress:/code
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    env_file: .env
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal    

  ipower-nginx:
    image: nginx:latest
    container_name: ipower-nginx
    depends_on:
      - ipower-php
    volumes:
      - ./wordpress:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'

##    environment:
##      VIRTUAL_HOST: 'ipower.local,*.ipower.local'
#
  ipower-pma:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    depends_on:
      - ipower-db
    env_file: .env
    environment:
      PMA_HOST: ipower-db
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
#
##  composer:
##    image: composer/composer
##    container_name: ipower-composer
##    working_dir: /var/www/html
##    restart: 'no'
##    volumes:
##      - ./src:/var/www/html:rw,cached
#      
